* Tech
** 2015
*** May
**** Linux tcpdump命令详解				    :tcpdump:network:
http://www.cnblogs.com/ggjucheng/archive/2012/01/14/2322659.html
**** Getting Organized with Org Mode			      :orgmode:emacs:
[[http://correl.phoenixinquis.net/2014/11/25/getting-organized-with-org-mode.html]]
**** 翻译：理解TCP/IP网络栈&编写网络应用 		 :network:kernel:tcp:
http://blog.2baxb.me/archives/1174
http://blog.2baxb.me/archives/1190
**** 深入浅出Mesos						      :mesos:
http://www.infoq.com/cn/articles/analyse-mesos-part-02
**** Docker Without Docker				     :docker:systemd:
https://chimeracoder.github.io/docker-without-docker/#1
**** Project Tungsten：让Spark将硬件性能压榨到极限	  :spark:performance:
http://www.csdn.net/article/2015-04-30/2824591
**** OpenWrt路由器开发						    :openwrt:
http://segmentfault.com/a/1190000002721224
**** 从外网 SSH 进局域网，反向代理+正向代理解决方案		  :ssh:proxy:
http://segmentfault.com/a/1190000002718360
**** Deprecating Non-Secure HTTP				  :ssl:https:
https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/
**** Upgrade Insecure Requests					   :ssl:hsts:
http://www.w3.org/TR/upgrade-insecure-requests/
**** VXLAN Overview					      :vxlan:network:
http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-729383.html
**** Qemu and the Kernel
http://www.linux-magazine.com/Online/Features/Qemu-and-the-Kernel
**** A Quick Introduction to LXD				    :lxc:lxd:
http://blog.scottlowe.org/2015/05/06/quick-intro-lxd/
**** Optimize Python with Closures			:python:optimization:
http://tech.magnetic.com/2015/05/optimize-python-with-closures.html
**** 关于Ceph现状与未来的一些思考				       :ceph:
https://www.ustack.com/blog/sikao/
**** DockOne技术分享（二）：集群规模下日志处理和网络方案	     :docker:
http://dockone.io/article/355
**** Static Linking Considered Harmful				       :link:
http://www.akkadia.org/drepper/no_static_linking.html
**** Docker日志自动化: ElasticSearch, Logstash, Kibana, 以及Logspout :docker:
http://dockone.io/article/373
**** Nmap Examples For Network Admins				       :namp:
http://teknixx.com/nmap-examples-for-network-admins/
**** How debugger works						 :gdb:ptrace:
http://www.alexonlinux.com/how-debugger-works
****  Transport Layer Security (TLS) Jump Start				:TLS:
https://www.ietf.org/id/draft-vkrasnov-tls-jumpstart-00.txt
**** Python coroutines with async and await		       :python:async:
http://lwn.net/Articles/643786/
**** PEP 492 vs. PEP 3152, new round			       :python:async:
https://lwn.net/Articles/644128/
**** Moving to ES6 from CoffeeScript					:es6:
https://gist.github.com/danielgtaylor/0b60c2ed1f069f118562
**** Learning C with gdb						:gdb:
https://www.recurse.com/blog/5-learning-c-with-gdb
**** Actual Zero-Downtime with HAProxy
https://medium.com/@Drew_Stokes/actual-zero-downtime-with-haproxy-18318578fde6
**** Unix filesystems: How mv can be dangerous
http://jstimpfle.de/fun/mv.html
**** Unix Shells: Bash, Fish, Ksh, Tcsh, Zsh			      :shell:
http://hyperpolyglot.org/unix-shells
**** Tuning Docker with the newest security enhancements     :docker:selinux:
http://opensource.com/business/15/3/docker-security-tuning
**** Multipath routing on a Raspberry Pi 2咸
http://www.whizzy.org/2015/05/multipathrouting-rasppi2/
**** SSH 远程连接服务慢的解决方案					:ssh:
https://linux.cn/article-5497-weibo.html
**** 利用google authenticator构建平台的otp动态口令
http://xiaorui.cc/2014/11/09/%E5%88%A9%E7%94%A8google-authenticator%E6%9E%84%E5%BB%BA%E5%B9%B3%E5%8F%B0%E7%9A%84otp%E5%8A%A8%E6%80%81%E5%8F%A3%E4%BB%A4/
**** Socket Sharding in NGINX Release 1.9.1			      :nginx:
http://nginx.com/blog/socket-sharding-nginx-release-1-9-1/
**** Optimizing Python - a Case Study			:python:optimization:
https://www.airpair.com/python/posts/optimizing-python-code
**** DOCKER AND THE THREE WAYS OF DEVOPS			     :devops:
http://blog.docker.com/2015/05/docker-three-ways-ops/
**** Dynamic Linking						       :link:
http://harmful.cat-v.org/software/dynamic-linking/
**** SSD: how to optimize your Solid State Drive			:ssd:
https://sites.google.com/site/easylinuxtipsproject/ssd

*** Jun
**** DockOne技术分享（五）：Docker网络详解及Libnetwrok前瞻 	     :docker:
http://dockone.io/article/402
**** I/O Schedulers						      :linux:
http://www.makelinux.net/books/lkd2/ch13lev1sec5
**** Linux Storage Stack Diagramm		       :linux:kernel:stoarge:
https://www.thomas-krenn.com/de/wiki/Linux_I/O_Stack_Diagramm
**** Linux I/O Scheduler					   :linux:io:
https://www.thomas-krenn.com/de/wiki/Linux_I/O_Scheduler
**** A Toolkit To Measure Basic System Performance And OS Jitter :performance:
http://highscalability.com/blog/2015/5/27/a-toolkit-to-measure-basic-system-performance-and-os-jitter.html
**** Making a toy programming language in Lua, part 1			:lua:
http://www.playwithlua.com/?p=66
**** mesos, omega, borg: a survey				 :borg:mesos:
http://www.umbrant.com/blog/2015/mesos_omega_borg_survey.html
**** Bash associative array examples				      :shell:
http://www.artificialworlds.net/blog/2012/10/17/bash-associative-array-examples/
**** How to Backup Linux? 15 rsync Command Examples		      :rsync:
     http://www.thegeekstuff.com/2010/09/rsync-command-examples/
**** True Zero Downtime HAProxy Reloads				    :haproxy:
http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html
*** Aug
**** How PAM works						  :pam:linux:
http://www.tuxradar.com/content/how-pam-works
**** How TCP backlog works in Linux				:tcp:backlog:
http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
**** Simplify Your Life With an SSH Config File				:ssh:
http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/
**** SSH Kung Fu							:ssh:
http://blog.tjll.net/ssh-kung-fu/
**** Google DNS劫持背后的技术分析					:bgp:
http://drops.wooyun.org/papers/1207
**** BlackHat议题分析：浅析BGP劫持利用					:bgp:
http://www.freebuf.com/articles/network/75305.html
**** Dynamic Reconfiguration with NGINX Plus			      :nginx:
https://www.nginx.com/blog/dynamic-reconfiguration-with-nginx-plus/
**** Mitigating DDoS Attacks with NGINX and NGINX Plus		      :nginx:
https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/
**** How widely used are security based HTTP response headers?	       :http:
https://scotthelme.co.uk/how-widely-used-are-security-based-http-response-headers/
*** Sep
**** How to receive a million packets per second	 :network:cloudflare:
https://blog.cloudflare.com/how-to-receive-a-million-packets/
**** How to achieve low latency with 10Gbps Ethernet
https://blog.cloudflare.com/how-to-achieve-low-latency/
**** Kernel bypass
https://blog.cloudflare.com/kernel-bypass/
* Blog

** Individuals
*** Axb的自我修养
http://blog.2baxb.me/
*** 火丁笔记
http://huoding.com/
*** nixCraft
http://www.cyberciti.biz/

** Companys
*** cloudflare blog
https://blog.cloudflare.com/
*** unitedstack
https://www.ustack.com/blog/

** Organizations
* Kernel
** live patch
- A rough patch for live patching :: http://lwn.net/Articles/634649/
** network

*** userspace network stacks
- Running the kernel in library mode :: http://lwn.net/Articles/639333/
- Library Operating System for Linux  :: http://www.slideshare.net/hajimetazaki/library-operating-system-for-linux-netdev01
* Virtualization
** network
*** Network virtualization with VXLAN
http://vincent.bernat.im/en/blog/2012-multicast-vxlan.html
*** Flockport labs - LXC and VXLAN
http://www.flockport.com/flockport-labs-lxc-and-vxlan/
*** Enhanced VXLAN: Who Needs Multicast?
http://adamraffe.com/2013/06/24/enhanced-vxlan-who-needs-multicast/
* Security
** ssl
*** The Logjam Attack
https://weakdh.org/
**** Logjam: the latest TLS vulnerability explained
https://blog.cloudflare.com/logjam-the-latest-tls-vulnerability-explained/


* Command
rsync -avzhP <[[user@]]host1:]directory1> <[[user@]]host2:]directory2>

* References
** lua-users.org							:lua:
http://lua-users.org/
