
* Tech
** 2015
*** May
**** Linux tcpdump命令详解				    :tcpdump:network:
http://www.cnblogs.com/ggjucheng/archive/2012/01/14/2322659.html
**** Getting Organized with Org Mode			      :orgmode:emacs:
[[http://correl.phoenixinquis.net/2014/11/25/getting-organized-with-org-mode.html]]
**** 翻译：理解TCP/IP网络栈&编写网络应用 		 :network:kernel:tcp:
http://blog.2baxb.me/archives/1174
http://blog.2baxb.me/archives/1190
**** 深入浅出Mesos						      :mesos:
http://www.infoq.com/cn/articles/analyse-mesos-part-02
**** Docker Without Docker				     :docker:systemd:
https://chimeracoder.github.io/docker-without-docker/#1
**** Project Tungsten：让Spark将硬件性能压榨到极限	  :spark:performance:
http://www.csdn.net/article/2015-04-30/2824591
**** OpenWrt路由器开发						    :openwrt:
http://segmentfault.com/a/1190000002721224
**** 从外网 SSH 进局域网，反向代理+正向代理解决方案		  :ssh:proxy:
http://segmentfault.com/a/1190000002718360
**** Deprecating Non-Secure HTTP				  :ssl:https:
https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/
**** Upgrade Insecure Requests					   :ssl:hsts:
http://www.w3.org/TR/upgrade-insecure-requests/
**** VXLAN Overview					      :vxlan:network:
http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-729383.html
**** Qemu and the Kernel
http://www.linux-magazine.com/Online/Features/Qemu-and-the-Kernel
**** A Quick Introduction to LXD				    :lxc:lxd:
http://blog.scottlowe.org/2015/05/06/quick-intro-lxd/
**** Optimize Python with Closures			:python:optimization:
http://tech.magnetic.com/2015/05/optimize-python-with-closures.html
**** 关于Ceph现状与未来的一些思考				       :ceph:
https://www.ustack.com/blog/sikao/
**** DockOne技术分享（二）：集群规模下日志处理和网络方案	     :docker:
http://dockone.io/article/355
**** Static Linking Considered Harmful				       :link:
http://www.akkadia.org/drepper/no_static_linking.html
**** Docker日志自动化: ElasticSearch, Logstash, Kibana, 以及Logspout :docker:
http://dockone.io/article/373
**** Nmap Examples For Network Admins				       :namp:
http://teknixx.com/nmap-examples-for-network-admins/
**** How debugger works						 :gdb:ptrace:
http://www.alexonlinux.com/how-debugger-works
****  Transport Layer Security (TLS) Jump Start				:TLS:
https://www.ietf.org/id/draft-vkrasnov-tls-jumpstart-00.txt
**** Python coroutines with async and await		       :python:async:
http://lwn.net/Articles/643786/
**** PEP 492 vs. PEP 3152, new round			       :python:async:
https://lwn.net/Articles/644128/
**** Moving to ES6 from CoffeeScript					:es6:
https://gist.github.com/danielgtaylor/0b60c2ed1f069f118562
**** Learning C with gdb						:gdb:
https://www.recurse.com/blog/5-learning-c-with-gdb
**** Actual Zero-Downtime with HAProxy
https://medium.com/@Drew_Stokes/actual-zero-downtime-with-haproxy-18318578fde6
**** Unix filesystems: How mv can be dangerous
http://jstimpfle.de/fun/mv.html
**** Unix Shells: Bash, Fish, Ksh, Tcsh, Zsh			      :shell:
http://hyperpolyglot.org/unix-shells
**** Tuning Docker with the newest security enhancements     :docker:selinux:
http://opensource.com/business/15/3/docker-security-tuning
**** Multipath routing on a Raspberry Pi 2咸
http://www.whizzy.org/2015/05/multipathrouting-rasppi2/
**** SSH 远程连接服务慢的解决方案					:ssh:
https://linux.cn/article-5497-weibo.html
**** 利用google authenticator构建平台的otp动态口令
http://xiaorui.cc/2014/11/09/%E5%88%A9%E7%94%A8google-authenticator%E6%9E%84%E5%BB%BA%E5%B9%B3%E5%8F%B0%E7%9A%84otp%E5%8A%A8%E6%80%81%E5%8F%A3%E4%BB%A4/
**** Socket Sharding in NGINX Release 1.9.1			      :nginx:
http://nginx.com/blog/socket-sharding-nginx-release-1-9-1/
**** Optimizing Python - a Case Study			:python:optimization:
https://www.airpair.com/python/posts/optimizing-python-code
**** DOCKER AND THE THREE WAYS OF DEVOPS			     :devops:
http://blog.docker.com/2015/05/docker-three-ways-ops/
**** Dynamic Linking						       :link:
http://harmful.cat-v.org/software/dynamic-linking/
**** SSD: how to optimize your Solid State Drive			:ssd:
https://sites.google.com/site/easylinuxtipsproject/ssd

*** Jun
**** DockOne技术分享（五）：Docker网络详解及Libnetwrok前瞻 	     :docker:
http://dockone.io/article/402
**** I/O Schedulers						      :linux:
http://www.makelinux.net/books/lkd2/ch13lev1sec5
**** Linux Storage Stack Diagramm		       :linux:kernel:stoarge:
https://www.thomas-krenn.com/de/wiki/Linux_I/O_Stack_Diagramm
**** Linux I/O Scheduler					   :linux:io:
https://www.thomas-krenn.com/de/wiki/Linux_I/O_Scheduler
**** A Toolkit To Measure Basic System Performance And OS Jitter :performance:
http://highscalability.com/blog/2015/5/27/a-toolkit-to-measure-basic-system-performance-and-os-jitter.html
**** Making a toy programming language in Lua, part 1			:lua:
http://www.playwithlua.com/?p=66
**** mesos, omega, borg: a survey				 :borg:mesos:
http://www.umbrant.com/blog/2015/mesos_omega_borg_survey.html
**** Bash associative array examples				      :shell:
http://www.artificialworlds.net/blog/2012/10/17/bash-associative-array-examples/
**** How to Backup Linux? 15 rsync Command Examples		      :rsync:
http://www.thegeekstuff.com/2010/09/rsync-command-examples/
**** True Zero Downtime HAProxy Reloads				    :haproxy:
http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html
*** Aug
**** How PAM works						  :pam:linux:
http://www.tuxradar.com/content/how-pam-works
**** How TCP backlog works in Linux				:tcp:backlog:
http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
**** Simplify Your Life With an SSH Config File				:ssh:
http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/
**** SSH Kung Fu							:ssh:
http://blog.tjll.net/ssh-kung-fu/
**** Google DNS劫持背后的技术分析					:bgp:
http://drops.wooyun.org/papers/1207
**** BlackHat议题分析：浅析BGP劫持利用					:bgp:
http://www.freebuf.com/articles/network/75305.html
**** Dynamic Reconfiguration with NGINX Plus			      :nginx:
https://www.nginx.com/blog/dynamic-reconfiguration-with-nginx-plus/
**** Mitigating DDoS Attacks with NGINX and NGINX Plus		      :nginx:
https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/
**** How widely used are security based HTTP response headers?	       :http:
https://scotthelme.co.uk/how-widely-used-are-security-based-http-response-headers/
*** Sep
**** How to receive a million packets per second	 :network:cloudflare:
https://blog.cloudflare.com/how-to-receive-a-million-packets/
**** How to achieve low latency with 10Gbps Ethernet
https://blog.cloudflare.com/how-to-achieve-low-latency/
**** Kernel bypass
https://blog.cloudflare.com/kernel-bypass/
**** What I Wish I Knew When Learning Haskell			    :haskell:
http://dev.stephendiehl.com/hask/
**** Implementing a JIT Compiled Language with Haskell and LLVM :haskell:llvm:
http://www.stephendiehl.com/llvm/
**** What's New in CPUs Since the 80s and How Does It Affect Programmers? :cpu:
http://danluu.com/new-cpu-features/
**** Dynamic TLS certificates with OpenResty and ssl_certificate_by_lua :nginx:
https://litespeed.io/dynamic-tls-certificates-with-openresty-and-ssl_certificate_by_lua/
****  makeself - Make self-extractable archives on Unix		      :shell:
http://stephanepeter.com/makeself/
**** C++ Core Guidelines						  :c++:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md
**** Python Goto						     :python:
https://github.com/snoack/python-goto
**** IO负载高的来源定位						   :linux:io:
http://www.cnblogs.com/cenalulu/archive/2013/04/12/3016714.html
**** Hadoop安装教程_单机/伪分布式配置				     :hadoop:
http://www.powerxing.com/install-hadoop/
**** It’s Time for Low Latency					    :latency:
https://www.evernote.com/shard/s4/sh/da079cd2-c272-4b13-9a10-c70a213873b4/00985892a73d80a0
**** Virtio: An I/O virtualization framework for Linux		    :virtual:
http://www.ibm.com/developerworks/library/l-virtio/
*** Oct
**** Using imagemagick, awk and kmeans to find dominant colors in images :color:
http://javier.io/blog/en/2015/09/30/using-imagemagick-and-kmeans-to-find-dominant-colors-in-images.html
**** Pushing the Limits of Kernel Networking			    :network:
http://rhelblog.redhat.com/2015/09/29/pushing-the-limits-of-kernel-networking/
**** A PATTERN FOR OPTIMIZING GO					 :go:
http://blog.signalfx.com/a-pattern-for-optimizing-go
**** Do not let your CDN betray you: Use Subresource Integrity		:web:
https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/
**** JavaScript goes to Asynchronous city			 :javascript:
http://blogs.msdn.com/b/eternalcoding/archive/2015/09/30/javascript-goes-to-asynchronous-city.aspx
**** ECMAScript 6入门						 :javascript:
http://es6.ruanyifeng.com
**** container compilation					  :container:
http://doger.io/
**** 1M QPS with nginx and Ubuntu 12.04 on EC2		:performance:network:
http://strace.co/91xqyPJ#http://datacratic.com/site/blog/1m-qps-nginx-and-ubuntu-1204-ec2
**** The Lost Art of C Structure Packing			  :c:packing:
http://www.catb.org/esr/structure-packing/
**** Intel VT-d						      :virtual:intel:
https://software.intel.com/en-us/articles/intel-virtualization-technology-for-directed-io-vt-d-enhancing-intel-platforms-for-efficient-virtualization-of-io-devices
**** bcc: Taming Linux 4.3+ Tracing Superpowers			:linux:trace:
http://www.brendangregg.com/blog/2015-09-22/bcc-linux-4.3-tracing.html
**** The LMAX Architecture					  :disruptor:
http://martinfowler.com/articles/lmax.html
**** LMAX Disruptor
http://lmax-exchange.github.io/disruptor/files/Disruptor-1.0.pdf
**** How to filter, split or merge pcap files on Linux	  :tcpdump:wireshark:
http://xmodulo.com/filter-split-merge-pcap-linux.html
**** From REST to GraphQL					    :graphql:
https://blog.jacobwgillespie.com/from-rest-to-graphql-b4e95e94c26b
**** Dublin Traceroute						    :network:
https://dublin-traceroute.net/README.md
**** Evolving How We Learn Systems with Lessons from Programming in the Large
http://hoverbear.org/2015/09/12/understand-over-guesswork/
**** SendIP							    :network:
http://snad.ncsl.nist.gov/ipv6//sendip.html
**** Parallelism, Concurrency, and Asynchrony in Perl 6		      :perl6:
http://jnthn.net/papers/2015-yapcasia-concurrency.pdf
**** QEMU Internals						       :qemu:
     http://ellcc.org/ellcc/share/doc/qemu/qemu-tech.html
*** Nov
**** decrypting secure tunnels						:ssh:
http://paperlined.org/sysadmin/network/decrypting_secure_tunnels.html
**** Updating Daylight Saving Time on Linux
https://chrisjean.com/updating-daylight-saving-time-on-linux/
**** tmux Copy & Paste on OS X: A Better Future			       :tmux:
https://robots.thoughtbot.com/tmux-copy-paste-on-os-x-a-better-future
**** get current time in seconds since the Epoch on Linux, Bash	       :bash:
http://stackoverflow.com/questions/1092631/get-current-time-in-seconds-since-the-epoch-on-linux-bash
**** Profiling Python in Production				     :python:
https://www.nylas.com/blog/performance
**** systemd-networkd Migration and Benchmarks: Fast and Furious    :systemd:
https://tlhp.cf/systemd-networkd-migration-and-benchmarks/
**** Swagger							:api:restful:
http://swagger.io/
**** Creating purpose-built TinyCoreLinux Images
http://fabianstumpf.de/articles/tinycore_images.htm
**** Visual Cryptography
http://www.datagenetics.com/blog/november32013/
**** fwupd: Updating Firmware in Linux
http://www.fwupd.org/index.html
**** Emacs for vi users						      :emacs:
http://www.elmindreda.org/emacs.html

**** A CEO's Guide to Emacs					      :emacs:
https://blog.fugue.co/2015-11-11-guide-to-emacs.html

**** Squashing Docker images with Btrfs
http://kamalmarhubi.com/blog/2015/11/27/squashing-docker-images-with-btrfs/

**** TCP over IP Anycast - Pipe dream or Reality?
https://engineering.linkedin.com/network-performance/tcp-over-ip-anycast-pipe-dream-or-reality

**** How LinkedIn used PoPs and RUM to make dynamic content download 25% faster
https://engineering.linkedin.com/performance/how-linkedin-used-pops-and-rum-make-dynamic-content-download-25-faster

**** TCP Anycast - Don't believe the FUD
https://www.nanog.org/meetings/nanog37/presentations/matt.levine.pdf

**** Why you should understand (a little) about TCP		:tcp:nodelay:
http://jvns.ca/blog/2015/11/21/why-you-should-understand-a-little-about-tcp/

**** Changes in the TLS certificate ecosystem, part 2	    :tls:certificate:
http://lwn.net/Articles/664240/

**** The secret message hidden in every HTTP/2 connection
http://blog.jgc.org/2015/11/the-secret-message-hidden-in-every.html

**** coreutils gotchas
http://www.pixelbeat.org/docs/coreutils-gotchas.html

**** Magit! A Git Porcelain inside Emacs 			      :emacs:
http://magit.vc/

**** Linux Performance Analysis in 60,000 Milliseconds
http://techblog.netflix.com/2015/11/linux-performance-analysis-in-60s.html

**** Dd - Destroyer of Disks					      :Linux:
http://www.noah.org/wiki/Dd_-_Destroyer_of_Disks

**** Containerizing in the real world . . . of Minecraft	     :docker:
http://googlecloudplatform.blogspot.jp/2015/11/containerizing-in-the-real-world-of-Minecraft.html
*** Dec
**** http2 explained
http://http2-explained.haxx.se/
**** 关于启用 HTTPS 的一些经验分享
https://imququ.com/post/sth-about-switch-to-https.html
**** 3 Second Sandwich —— How do card networks work?		    :payment:
https://getmondo.co.uk/blog/2015/12/02/3-second-sandwich/
**** alda  —— A music programming language for musicians
https://github.com/alda-lang/alda
**** Overlay Network Performance of Docker			      :vxlan:
http://mustafaak.in/2015/12/05/docker-overlay-performance.html
**** If I were designing Python's import from scratch		     :python:
http://www.snarky.ca/if-i-were-designing-imort-from-scratch
**** HTTP/2 is here! Goodbye SPDY? Not quite yet			:tls:
https://blog.cloudflare.com/introducing-http2/
**** The uWSGI Swiss Army Knife					     :python:
https://lincolnloop.com/blog/uwsgi-swiss-army-knife/
**** 可靠分布式系统基础 Paxos 的直观解释
http://drmingdrmer.github.io/tech/distributed/2015/11/11/paxos-slide.html

**** Emacs Lisp Animations
http://dantorop.info/project/emacs-animation/

**** rsync.net: ZFS Replication to the cloud is finally here—and it’s fast
http://arstechnica.com/information-technology/2015/12/rsync-net-zfs-replication-to-the-cloud-is-finally-here-and-its-fast/

**** Spark Streaming 源码解析系列
https://github.com/proflin/CoolplaySpark
**** dotfiles -- Your unofficial guide to dotfiles on GitHub.
https://dotfiles.github.io/
**** To cd or not to cd						      :shell:
http://www.redpill-linpro.com/sysadvent/2015/12/02/cd-tips.html
**** Changing a process’ file descriptor on the fly
http://www.redpill-linpro.com/sysadvent/2015/12/04/changing-a-process-file-descriptor-with-gdb.html
**** Java工程师成神之路
     http://www.hollischuang.com/archives/489
**** IPFS：替代HTTP的分布式网络协议
http://www.infoq.com/cn/articles/ipfs
**** Install Arch Infographic
https://imgur.com/Hokk8sK
**** A Python Interpreter Written in Python
http://aosabook.org/en/500L/a-python-interpreter-written-in-python.html
**** Moores law hits the roof						:cpu:
http://www.agner.org/optimize/blog/read.php?i=417


** 2016
   
*** Jan

**** The Elements of Python Style
https://github.com/amontalenti/elements-of-python-style

**** A Unikernel Firewall for QubesOS
http://roscidus.com/blog/blog/2016/01/01/a-unikernel-firewall-for-qubesos/

**** 32C3 CTF: Docker writeup
https://kitctf.de/writeups/32c3ctf/docker/

**** Zopfli Optimization: Literally Free Bandwidth
http://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/

**** Remap the Kernel						       :rust:
http://os.phil-opp.com/remap-the-kernel.html

**** Why `print` became a function in Python 3
http://www.snarky.ca/why-print-became-a-function-in-python-3

**** intermezzOS						  :kernel:os:
http://intermezzos.github.io/

**** es6-cheatsheet
https://github.com/DrkSephy/es6-cheatsheet

**** Assembly is Too High Level: SIB Doubles
http://xlogicx.net/?p=456

**** A Book about Qt5
http://qmlbook.github.io/

**** Unikernel Systems
http://unikernel.com/

**** dead or alive: Linux LibOS project in 2016
https://github.com/thehajime/blog/issues/1

**** 浏览器端的 9 种缓存机制 					      :cache:
https://linux.cn/article-6833-1.html

****  Inappropriate TCP Resets Considered Harmful
https://tools.ietf.org/html/rfc3360

**** Remap the Kernel
http://os.phil-opp.com/remap-the-kernel.html

**** A Python Interpreter Written in Python
http://aosabook.org/en/500L/a-python-interpreter-written-in-python.html

**** ScyllaDB: world's fastest NoSQL column store database
http://www.scylladb.com/

*** Feb

**** Writing my own init with Go - Part 1
http://www.mustafaak.in/2016/02/08/writing-my-own-init-with-go.html

**** Windows 10 TH2 (v1511) Console Host Enhancements		    :console:
http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-%28v1511%29-Console-Host-Enhancements

**** Terminal codes (ANSI/VT100) introduction			    :console:
http://wiki.bash-hackers.org/scripting/terminalcodes

**** A Better Varargs							  :c:
http://codeacumen.info/post/a-better-varargs/

**** The Princeton Bitcoin textbook is now freely available
https://freedom-to-tinker.com/blog/randomwalker/the-princeton-bitcoin-textbook-is-now-freely-available/

**** Linux: Bash Delete All Files In Directory Except Few
http://www.cyberciti.biz/faq/linux-bash-delete-all-files-in-directory-except-few/
*** Mar
**** Infix Operators in Python
http://tomerfiliba.com/blog/Infix-Operators/
**** The Idiomatic Way to Merge Dictionaries in Python
https://treyhunner.com/2016/02/how-to-merge-dictionaries-in-python/
**** boltons boltons should be builtins
https://boltons.readthedocs.org/en/latest/index.html
**** The origins of the class Meta idiom in python
http://mapleoin.github.io/perma/python-class-meta
**** TCP packet drop analysis			     :tcpdump:retran:network:
http://www.unleashnetworks.com/blog/?p=437
**** Flushing out Leaky Taps v2			      :tshark:retran:network:
http://smusec.blogspot.jp/2012/03/flushing-out-leaky-taps-v2.html
**** Using advanced tcpdump filters				    :tcpdump:
https://support.f5.com/kb/en-us/solutions/public/2000/200/sol2289.html#Uni
**** tcpdump tips
http://blog.mosinu.com/?p=239
**** How the heck does async/await work in Python 3.5?
http://www.snarky.ca/how-the-heck-does-async-await-work-in-python-3-5
**** Installing (encrypted) Arch Linux on an Apple MacBook Pro
https://visual-assault.org/2016/03/05/install-encrypted-arch-linux-on-apple-macbook-pro/
**** Python Mocking 101: Fake It Before You Make It
https://blog.fugue.co/2016-02-11-python-mocking-101.html
**** How does perf work? (in which we read the Linux kernel source)
http://jvns.ca/blog/2016/03/12/how-does-perf-work-and-some-questions/
**** Eliminating Delays From systemd-journald, Part 1
https://coreos.com/blog/eliminating-journald-delays-part-1.html
**** Autoconf Tutorial Part-1
http://www.idryman.org/blog/2016/03/10/autoconf-tutorial-1/
**** LXD 2.0: Blog post series [0/12]				      :linux:
https://www.stgraber.org/2016/03/11/lxd-2-0-blog-post-series-012/
**** Maglev: A Fast and Reliable Software Network Load Balancer
http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf
**** Dropping Packets in Ubuntu Linux using tc and iptables
https://sandilands.info/sgordon/dropping-packets-in-ubuntu-linux-using-tc-and-iptables
**** Lossless Gigabit Remote Packet Capture With Linux		    :tcpdump:
http://staff.washington.edu/corey/gulp/
**** Linux Network Stack Administration: A Developer’s Approach
http://opensourceforu.efytimes.com/2009/08/linux-network-stack-administration-a-developers-approach/
**** Understanding and optimizing Network utilization
http://careers.directi.com/display/tu/Understanding+and+optimizing+Network+utilization
**** Using NFQUEUE and libnetfilter_queue		      :iptable:linux:
https://home.regit.org/netfilter-en/using-nfqueue-and-libnetfilter_queue/
**** TCP Performance problems caused by interaction between Nagle’s Algorithm and Delayed ACK :tcptrace:
http://www.stuartcheshire.org/papers/NagleDelayedAck/
*** Apr
****  I stared into the fontconfig, and the fontconfig stared back at me
https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/
**** The Definitive Guide to Linux System Calls                       :linux:
http://blog.packagecloud.io/eng/2016/04/05/the-definitive-guide-to-linux-system-calls/
**** Linux Troubleshooting Cheatsheet: strace, htop, lsof, tcpdump, iftop & sysdig
https://sysdig.com/blog/linux-troubleshooting-cheatsheet/
**** Python Virtual Environments - a Primer
https://realpython.com/blog/python/python-virtual-environments-a-primer/
**** Bootstrap 4 Cheat Sheet
http://hackerthemes.com/bootstrap-cheatsheet
*** May
**** The Ars guide to building a Linux router from scratch
http://arstechnica.com/gadgets/2016/04/the-ars-guide-to-building-a-linux-router-from-scratch/
**** How To Install Puppet 4 in a Master-Agent Setup on Ubuntu 14.04
https://www.digitalocean.com/community/tutorials/how-to-install-puppet-4-in-a-master-agent-setup-on-ubuntu-14-04
**** A simple way to install and configure puppet on CentOS 6
http://techarena51.com/index.php/a-simple-way-to-install-and-configure-a-puppet-server-on-linux/
**** puppet tutorial -- example42
http://www.example42.com/tutorials/PuppetTutorial
**** uvloop: Blazing fast Python networking
http://magic.io/blog/uvloop-blazing-fast-python-networking/
**** Toil is a workflow engine entirely written in Python
http://toil.readthedocs.io/en/latest/
**** SSH for Fun and Profit
https://karla.io/2016/04/30/ssh-for-fun-and-profit.html
**** Cipherli.st Strong Ciphers for Apache, nginx and Lighttpd
https://cipherli.st/
**** 6-Part Guide to NGINX Application Performance Optimization :tcp:performance:
https://www.maxcdn.com/blog/nginx-application-performance-optimization/
**** SuperTCP                                                   :performance:
https://www.supertcp.com/technology-overview/
**** A list of command line tools for manipulating structured text data :cli:
https://github.com/dbohdan/structured-text-tools
**** Kplugs a user-mode interface for plugging into the linux kernel   :perf:
http://www.kplugs.org/
**** How to turn any syscall into an event: Introducing eBPF Kernel probes
https://blog.yadutaf.fr/2016/03/30/turn-any-syscall-into-event-introducing-ebpf-kernel-probes/
**** Docker for your users - Introducing user namespace
https://blog.yadutaf.fr/2016/04/14/docker-for-your-users-introducing-user-namespace/
**** Real World Microservices: When Services Stop Playing Well and Start Getting Real
https://blog.buoyant.io/2016/05/04/real-world-microservices-when-services-stop-playing-well-and-start-getting-real/
**** Advanced Ping: httping, dnsping, smtpping
http://blog.webernetz.net/2016/05/10/advanced-ping-httping-dnsping-smtpping/
**** Who Needs Git When You Got ZFS?
http://zef.me/blog/6023/who-needs-git-when-you-got-zfs
**** Large (UDP) Packets in IPv6
https://ripe72.ripe.net/wp-content/uploads/presentations/67-2016-05-23-bigipv6.pdf
**** Security brief: CoreOS Linux Alpha remote SSH issue
https://coreos.com/blog/security-brief-coreos-linux-alpha-remote-ssh-issue.html
**** Web-based SSH
https://en.wikipedia.org/wiki/Web-based_SSH
**** A tutorial for porting to autoconf & automake                 :autotool:
http://mij.oltrelinux.com/devel/autoconf-automake/
**** Step-By-Step Example of Autotools for Beginner
http://www.aireadfun.com/blog/2012/12/03/study-automake/
**** The Architecture of Open Source Applications
http://aosabook.org/en/index.html

**** Introduction to the Autotools (autoconf, automake, and libtool)
http://www.dwheeler.com/autotools/
**** netem                                                    :linux:network:
http://www.linuxfoundation.org/collaborate/workgroups/networking/netem

**** Host Tuning                        :tcp:performance:network:optimizatio:
http://fasterdata.es.net/host-tuning/

**** SSH服务的几个超时参数 以及 类似DDOS攻击的方法
https://yq.aliyun.com/articles/57903

**** Greenplum 大集群应该调整的sshd_config配置
http://www.atatech.org/articles/58918
*** Jun
**** 	Sikuli: Automate Anything You See on Screen (sikuli.org)
https://news.ycombinator.com/item?id=11859980

**** Why is a Rust executable large?
https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html
**** Shell Script Mistakes
http://www.pixelbeat.org/programming/shell_script_mistakes.html
**** Use the Unofficial Bash Strict Mode (Unless You Looove Debugging)
http://redsymbol.net/articles/unofficial-bash-strict-mode/
**** Easy Automated Snapshot-Style Backups with Linux and Rsync
http://www.mikerubel.org/computers/rsync_snapshots/
**** linux memory management for servers
https://dom.as/2016/05/13/linux-memory-management-for-servers/
**** Network support for TCP Fast Open
https://www.nanog.org/sites/default/files/Paasch_Network_Support.pdf
**** 10 Articles Every Programmer Must Read
http://javarevisited.blogspot.com/2014/05/10-articles-every-programmer-must-read.html
**** Monitoring and Tuning the Linux Networking Stack: Receiving Data
http://blog.packagecloud.io/eng/2016/06/22/monitoring-tuning-linux-networking-stack-receiving-data/
*** Jul
**** Kent Overstreet is creating bcachefs - a next generation Linux filesystem
https://www.patreon.com/bcachefs
**** Why do we use the Linux kernel's TCP stack?
http://jvns.ca/blog/2016/06/30/why-do-we-use-the-linux-kernels-tcp-stack/
**** How to Monitor Zookeeper
https://blog.serverdensity.com/how-to-monitor-zookeeper/
**** ZooKeeper In The Wild
https://events.linuxfoundation.org/sites/events/files/slides/ZooKeeper%20in%20the%20Wild.pdf
**** Use EJS to Template Your Node Application
https://scotch.io/tutorials/use-ejs-to-template-your-node-application
**** Hadoop architectural overview
https://www.datadoghq.com/blog/hadoop-architecture-overview/
*** Aug
**** HTTP Request Timings with cURL
http://blog.kenweiner.com/2014/11/http-request-timings-with-curl.html
**** WIKIBOOK openssh
https://en.wikibooks.org/wiki/OpenSSH
**** Why GNU Autotools is not my favorite build system
http://voices.canonical.com/jussi.pakkanen/2011/09/13/autotools/
**** TLS has exactly one performance problem: it is not used widely enough.
https://istlsfastyet.com/
**** Job queues, message queues and other queues. Almost all of them in one place.
http://queues.io/
**** Git Workflow Basics
https://blog.codeminer42.com/git-workflow-basics-d405746f6205
**** Introduction 2016 NUMA Deep Dive Series
http://frankdenneman.nl/2016/07/06/introduction-2016-numa-deep-dive-series/
**** gdb Debugging Full Example (Tutorial): ncurses
http://www.brendangregg.com/blog/2016-08-09/gdb-example-ncurses.html
**** TCP Puzzlers
https://www.joyent.com/blog/tcp-puzzlers
**** BPF - the forgotten bytecode
https://blog.cloudflare.com/bpf-the-forgotten-bytecode/
**** New (and Exciting!) Developments in Linux Tracing                  :bpf:
     http://events.linuxfoundation.org/sites/events/files/slides/tracing-linux-ezannoni-linuxcon-ja-2015_0.pdf
**** JIT native code generation for TensorFlow computation graphs using Python and LLVM
http://blog.christianperone.com/2016/08/jit-native-code-generation-for-tensorflow-computation-graphs-using-python-and-llvm/
* blog

** Individuals
*** Axb的自我修养
http://blog.2baxb.me/
*** 火丁笔记
http://huoding.com/
*** nixCraft
http://www.cyberciti.biz/

** Companys
*** cloudflare blog
https://blog.cloudflare.com/
*** unitedstack
https://www.ustack.com/blog/

** Organizations
*** Linux Audit - Linux security: Auditing, Hardening and Compliance
http://linux-audit.com/

* Kernel
** live patch
- A rough patch for live patching :: http://lwn.net/Articles/634649/
** network
   
*** userspace network stacks
- Running the kernel in library mode :: http://lwn.net/Articles/639333/
- Library Operating System for Linux  :: http://www.slideshare.net/hajimetazaki/library-operating-system-for-linux-netdev01

*** Queueing in the Linux Network Stack
https://www.coverfire.com/articles/queueing-in-the-linux-network-stack/
** Misc
*** Linux kernel development
https://github.com/0xAX/linux-insides/blob/master/Misc/contribute.md

* Virtualization
** network
*** Network virtualization with VXLAN
http://vincent.bernat.im/en/blog/2012-multicast-vxlan.html
*** Flockport labs - LXC and VXLAN
http://www.flockport.com/flockport-labs-lxc-and-vxlan/
*** Enhanced VXLAN: Who Needs Multicast?
http://adamraffe.com/2013/06/24/enhanced-vxlan-who-needs-multicast/
* Security
** ssl
*** The Logjam Attack
https://weakdh.org/
**** Logjam: the latest TLS vulnerability explained
https://blog.cloudflare.com/logjam-the-latest-tls-vulnerability-explained/
* Project
*** OSv operating system
http://osv.io/
*** 

* Command
rsync -avzhP <[[user@]]host1:]directory1> <[[user@]]host2:]directory2>

* References
** lua-users.org							:lua:
http://lua-users.org/
* Font & Ideogram 
** What's new in Unicode 9.0 ?
http://babelstone.blogspot.com/2016/01/whats-new-in-unicode-90.html
** The long, incredibly tortuous, and fascinating process of creating a Chinese font
http://qz.com/522079/the-long-incredibly-tortuous-and-fascinating-process-of-creating-a-chinese-font/
