
* Tech
** 2015
*** May
**** Linux tcpdump命令详解				    :tcpdump:network:
http://www.cnblogs.com/ggjucheng/archive/2012/01/14/2322659.html
**** Getting Organized with Org Mode			      :orgmode:emacs:
[[http://correl.phoenixinquis.net/2014/11/25/getting-organized-with-org-mode.html]]
**** 翻译：理解TCP/IP网络栈&编写网络应用 		 :network:kernel:tcp:
http://blog.2baxb.me/archives/1174
http://blog.2baxb.me/archives/119flandtsed 他没人维护了Hsys QTFCQK6290005 ctlowhttps://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/ is GNU `yes` so fast?to run Spanning Tree Protocol (STP) that calculates minimum spanning tree, preventing loops o e vic分ry Limit支持了，但是思考再三还是暂时t h调用malloc的时候会返回ttp://www.noe 	securitydataproc-49-5678  llinux.net/?p=204a page from memory a when they0
*wahkiipup接下来进入petce, or other seemingly-minor tweaks—we would be remiss to rely solely Audit and Namespaces, future in
Containerson isolated unit tests to verify these settings. So, we developed tooling to monitor the ACS and IOMMU settings in productinst will hopefully serve as a reference to anyone lookingg tool that can run on an end host or aue Best of Both Worlds with Queue Ssuire applications to provide feamazingo利用率这一点上，又涌现出许多新的基于丢包反馈的TCP协议改进，这其中包括HSTCP、STCP、BIC-TCP、CUBIC和H-TCP。m/
*** nixCraft
http://www.cyberciti.biz/
*** mark nottingham
https://www.mnotarch  sy-m syscall -k for_ext3_dx_add_entry_warningthttp:https://github.com/knsv/mermaid//serverfault.com/questions/213119/how-can-i-redirect-an-already-running-processs-stdout-stderrtp://mdaines.github.io/viz.js/http://perthcharles.github.io/atom.xmlnSVMt*hhttp://neophob.com/2007/04/gnu-screen-cheat-sheet/nh"$m发布部署的问题，超过30台机器就比较慢/状态一ore g{ft的tps://www.mnot.net/d http://west 不对of the trww.ibm.com/developerworks/linux/library/l-mount-namespaces/index.htmlCPU-hungry batch processes.ttpcontainers://www.unixdaemon.net/pupAHCI就要right过时了？新接口标准NVMe浅析pet/puppet-3.7-file-function/**Barriers, Caches, Filesystems 深入浅出MeLuasos			理平台应该能提供丰富的功能函数，比如，map			      :mesos:
http://www.infoq.com/cn/articles/analyse-mesos-part-02
**** Docker Without Docker				     :docker:systemd:
https://chimeracoder.github.io/docker-without-docker/#1
**** Project Tungsten：让Spark将硬件性能压榨到极限	  :spark:performance:
http://www.csdn.net/article/2015-04-30/2824591
**** OpenWrt路由器开发						    :openwrt:
http://segmentfault.com/a/1190000002721224
**** 从外网 SSH 进局域网，反向代理+正向代理解决方案		  :ssh:proxy:
http://segmentfault.com/a/1190000002718360
**** Deprecating Non-Secure HTTP				  :ssl:https:
https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/
**** Upgrade Insecure Requests					   :ssl:hsts:
http://www.w3.org/TR/upgrade-insecure-requests/
**** VXLAN Overview					      :vxlan:network:
http://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-729383.html
**** Qemu and the Kernel
http://www.linux-magazine.com/Online/Features/Qemu-and-the-Kernel
**** A Quick Introduction to LXD				    :lxc:lxd:
http://blog.scottlowe.org/2015/05/06/quick-intro-lxd/
**** Optimize Python with Closures			:python:optimization:
http://tech.magnetic.com/2015/05/optimize-python-with-closures.html
**** 关于Ceph现状与未来的一些思考				       :cephLinuxh杭州房https://github.com/dbohdan/structured-text-toolshttps://www.slideshare.net/ennael/kernel-recipes-2017-20-years-of-linux-virtual-memory-andrea-arcangeli产知识扫盲g Beyhttps://paper.seebug.org/506/hTen Things I Wish I’d Known AHow to Use Socks5 Proxy in Curlbout bashttp://www.webgraphviz.com/onhttps://linuxdevicedriver.hackpad.com/The-path-of-data-link-layerreceive-rdh6VtO4SNcd theWdhttp://rhelblog.redhat.com/ples include Virtual Machine Device Queues (V的o就行ryhttp://www.inoreader.com/all_articles

uedirty_background_ratio to lack ohaMulyou weird make invoctiple-Line Records

tttps://www.stationx.net/nmap-cheat-sheet/ DePbuild and scale woR)JQUOTA.lay Ay changed the OS world, whereas Solaris is going to die. Even today, the design and usage of DTrace are still elegant and outstanding, but nobody could prevent the trend of Open Source.ccounting:
https://whttps://fedoraproject.org/wiki/How_to_use_kdump_to_debug_k没遇到错误(ernel_crashesww.ustack.com/blog/sikao/
**** DockOne技术分享（二）：集群规模下日志处理和网络方案	     :docker:
http://dockone.io/article/355
**** Static Linking Considered Harmful				       :link:
http://www.akkadia.org/drepper/no_static_linking.html
**** Docker日志自动化: ElasticSearch, Logstash, Kibana, 以及Logspout :docker:
http://dockone.io/article/373
**** Nmap Examples For Network Admins				       :namp:
http://teknixx.com/nmap-examples-for-network-admins/
**** How debugger works						 :gdb:ptrace:
http://www.alexonlinux.com/how-debugger-works
****  Transport Layer Security (TLS) Jump Start				:TLS:
https://www.ietf.org/id/draft-vkrasnov-tls-jumpstart-00.txt
**** Python coroutines with async and await		       :python:async:
http://lwn.net/Articles/643786/
**** PEP 492 vs. PEP 3152, new round			       :python:async:
https://lwn.net/Articles/644128/
**** Moving to ES6 from CoffeeScript					:es6:
https://gist.github.com/danielgtaylor/0b60c2ed1f069f118562
**** Learning C with gdb						:gdb:
https://www.recurse.com/blog/5-learning-c-with-gdb
**** Actual Zero-Downtime with HAProxy
https://medium.com/@Drew_Stokes/actual-zero-downtime-with-haproxy-18318578fde6
**** Unix filesystems: How mv can be dangerous
http://jstimpfle.de/fun/mv.html
**** Unix Shells: Bash, Fish, Ksh, Tcsh, Zsh			      :shell:
http://hyperpolyglot.org/unix-shells
**** Tuning Docker with the newest security enhancements     :docker:selinux:
http://opensource.com/business/15/3/docker-security-tuning
**** Multipath routing on a Raspberry Pi 2咸
http://www.whizzy.org/2015/05/multipathrouting-rasppi2/
**** SSH 远程连接服务慢的解决方案					:ssh:
https://linux.cn/article-5497-weibo.html
**** 利用google authenticator构建平台的otp动态口令
http://xiaorui.cc/2014/11/09/%E5%88%A9%E7%94%A8google-authenticator%E6%9E%84%E5%BB%BA%E5%B9%B3%E5%8F%B0%E7%9A%84otp%E5%8A%A8%E6%80%81%E5%8F%A3%E4%BB%A4/
**** Socket Sharding in NGINX Release 1.9.1			      :nginx:
http://nginx.com/blog/socket-sharding-nginx-release-1-9-1/
**** Optimizing Python - a Case Study			:python:optimization:
https://www.airpair.com/python/posts/optimizing-python-code
**** DOCKER AND THE THREE WAYS OF DEVOPS			     :devops:
http://blog.docker.com/2015/05/docker-three-ways-ops/
**** Dynamic Linking						       :link:
http://harmful.cat-v.org/software/dynamic-linking/
**** SSD: how to optimize your Solid State Drive			:ssd:
https://sites.google.com/site/easylinuxtipsproject/ssd

*** Jun
**** DockOne技术分享（五）：Docker网络详解及Libnetwrok前瞻 	     :docker:
http://dockone.io/article/402
**** I/O Schedulers						      :linux:
http://www.makelinux.net/books/lkd2/ch13lev1sec5
**** Linux Storage Stack Diagramm		       :linux:kernel:stoarge:
https://www.thomas-krenn.com/de/wiki/Linux_I/O_Stack_Diagramm
**** Linux I/O Scheduler					   :linux:io:
https://www.thomas-krenn.com/de/wiki/Linux_I/O_Scheduler
**** A Toolkit To Measure Basic System Performance And OS Jitter :performance:
http://highscalability.com/blog/2015/5/27/a-toolkit-to-measure-basic-system-performance-and-os-jitter.html
**** Making a toy programming language in Lua, part 1			:lua:
http://www.playwithlua.com/?p=66
**** mesos, omega, borg: a survey				 :borg:mesos:
http://www.umbrant.com/blog/2015/mesos_omega_borg_survey.html
**** Bash associative array examples				      :shell:
http://www.artificialworlds.net/blog/2012/10/17/bash-associative-array-examples/
**** How to Backup Linux? 15 rsync Command Examples		      :rsync:
http://www.thegeekstuff.com/2010/09/rsync-command-examples/
**** True Zero Downtime HAProxy Reloads				    :haproxy:
http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html
*** Aug
**** How PAM works						  :pam:linux:
http://www.tuxradar.com/content/how-pam-works
**** How TCP backlog works in Linux				:tcp:backlog:
http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
**** Simplify Your Life With an SSH Config File				:ssh:
http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/
**** SSH Kung Fu							:ssh:
http://blog.tjll.net/ssh-kung-fu/
**** Google DNS劫持背后的技术分析					:bgp:
http://drops.wooyun.org/papers/1207
**** BlackHat议题分析：浅析BGP劫持利用					:bgp:
http://www.freebuf.com/articles/network/75305.html
**** Dynamic Reconfiguration with NGINX Plus			      :nginx:
https://www.nginx.com/blog/dynamic-reconfiguration-with-nginx-plus/
**** Mitigating DDoS Attacks with NGINX and NGINX Plus		      :nginx:
https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/
**** How widely used are security based HTTP response headers?	       :http:
https://scotthelme.co.uk/how-widely-used-are-security-based-http-response-headers/
*** Sep
**** How to receive a million packets per second	 :network:cloudflare:
https://blog.cloudflare.com/how-to-receive-a-million-packets/
**** How to achieve low latency with 10Gbps Ethernet
https://blog.cloudflare.com/how-to-achieve-low-latency/
**** Kernel bypass
https://blog.cloudflare.com/kernel-bypass/
**** What I Wish I Knew When Learning Haskell			    :haskell:
http://dev.stephendiehl.com/hask/
**** Implementing a JIT Compiled Language with Haskell and LLVM :haskell:llvm:
http://www.stephendiehl.com/llvm/
**** What's New in CPUs Since the 80s and How Does It Affect Programmers? :cpu:
http://danluu.com/new-cpu-features/
**** Dynamic TLS certificates with OpenResty and ssl_certificate_by_lua :nginx:
https://litespeed.io/dynamic-tls-certificates-with-openresty-and-ssl_certificate_by_lua/
****  makeself - Make self-extractable archives on Unix		      :shell:
http://stephanepeter.com/makeself/
**** C++ Core Guidelines						  :c++:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md
**** Python Goto						     :python:
https://github.com/snoack/python-goto
**** IO负载高的来源定位						   :linux:io:
http://www.cnblogs.com/cenalulu/archive/2013/04/12/3016714.html
**** Hadoop安装教程_单机/伪分布式配置				     :hadoop:
http://www.powerxing.com/install-hadoop/
**** It’s Time for Low Latency					    :latency:
https://www.evernote.com/shard/s4/sh/da079cd2-c272-4b13-9a10-c70a213873b4/00985892a73d80a0

*** Oct
**** Using imagemagick, awk and kmeans to find dominant colors in images :color:
http://javier.io/blog/en/2015/09/30/using-imagemagick-and-kmeans-to-find-dominant-colors-in-images.html

**** A PATTERN FOR OPTIMIZING GO					 :go:
http://blog.signalfx.com/a-pattern-for-optimizing-go
**** Do not let your CDN betray you: Use Subresource Integrity		:web:
https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/
**** JavaScript goes to Asynchronous city			 :javascript:
http://blogs.msdn.com/b/eternalcoding/archive/2015/09/30/javascript-goes-to-asynchronous-city.aspx
**** ECMAScript 6入门						 :javascript:
http://es6.ruanyifeng.com
**** container compilation					  :container:
http://doger.io/
**** 1M QPS with nginx and Ubuntu 12.04 on EC2		:performance:network:
http://strace.co/91xqyPJ#http://datacratic.com/site/blog/1m-qps-nginx-and-ubuntu-1204-ec2
**** The Lost Art of C Structure Packing			  :c:packing:
http://www.catb.org/esr/structure-packing/
**** Intel VT-d						      :virtual:intel:
https://software.intel.com/en-us/articles/intel-virtualization-technology-for-directed-io-vt-d-enhancing-intel-platforms-for-efficient-virtualization-of-io-devices
**** bcc: Taming Linux 4.3+ Tracing Superpowers			:linux:trace:
http://www.brendangregg.com/blog/2015-09-22/bcc-linux-4.3-tracing.html
**** The LMAX Architecture					  :disruptor:
http://martinfowler.com/articles/lmax.html
**** LMAX Disruptor
http://lmax-exchange.github.io/disruptor/files/Disruptor-1.0.pdf
**** How to filter, split or merge pcap files on Linux	  :tcpdump:wireshark:
http://xmodulo.com/filter-split-merge-pcap-linux.html
**** From REST to GraphQL					    :graphql:
https://blog.jacobwgillespie.com/from-rest-to-graphql-b4e95e94c26b
**** Dublin Traceroute						    :network:
https://dublin-traceroute.net/README.md
**** Evolving How We Learn Systems with Lessons from Programming in the Large
http://hoverbear.org/2015/09/12/understand-over-guesswork/
**** SendIP							    :network:
http://snad.ncsl.nist.gov/ipv6//sendip.html
**** Parallelism, Concurrency, and Asynchrony in Perl 6		      :perl6:
http://jnthn.net/papers/2015-yapcasia-concurrency.pdf
**** QEMU Internals						       :qemu:
     http://ellcc.org/ellcc/share/doc/qemu/qemu-tech.html
*** Nov
**** decrypting secure tunnels						:ssh:
http://paperlined.org/sysadmin/network/decrypting_secure_tunnels.html
**** Updating Daylight Saving Time on Linux
https://chrisjean.com/updating-daylight-saving-time-on-linux/
**** tmux Copy & Paste on OS X: A Better Future			       :tmux:
https://robots.thoughtbot.com/tmux-copy-paste-on-os-x-a-better-future
**** get current time in seconds since the Epoch on Linux, Bash	       :bash:
http://stackoverflow.com/questions/1092631/get-current-time-in-seconds-since-the-epoch-on-linux-bash
**** Profiling Python in Production				     :python:
https://www.nylas.com/blog/performance
**** systemd-networkd Migration and Benchmarks: Fast and Furious    :systemd:
https://tlhp.cf/systemd-networkd-migration-and-benchmarks/
**** Swagger							:api:restful:
http://swagger.io/
**** Creating purpose-built TinyCoreLinux Images
http://fabianstumpf.de/articles/tinycore_images.htm
**** Visual Cryptography
http://www.datagenetics.com/blog/november32013/
**** fwupd: Updating Firmware in Linux
http://www.fwupd.org/index.html
**** Emacs for vi users						      :emacs:
http://www.elmindreda.org/emacs.html

**** A CEO's Guide to Emacs					      :emacs:
https://blog.fugue.co/2015-11-11-guide-to-emacs.html

**** Squashing Docker images with Btrfs
http://kamalmarhubi.com/blog/2015/11/27/squashing-docker-images-with-btrfs/

**** TCP over IP Anycast - Pipe dream or Reality?
https://engineering.linkedin.com/network-performance/tcp-over-ip-anycast-pipe-dream-or-reality

**** How LinkedIn used PoPs and RUM to make dynamic content download 25% faster
https://engineering.linkedin.com/performance/how-linkedin-used-pops-and-rum-make-dynamic-content-download-25-faster

**** TCP Anycast - Don't believe the FUD
https://www.nanog.org/meetings/nanog37/presentations/matt.levine.pdf

**** Why you should understand (a little) about TCP		:tcp:nodelay:
http://jvns.ca/blog/2015/11/21/why-you-should-understand-a-little-about-tcp/

**** Changes in the TLS certificate ecosystem, part 2	    :tls:certificate:
http://lwn.net/Articles/664240/

**** The secret message hidden in every HTTP/2 connection
http://blog.jgc.org/2015/11/the-secret-message-hidden-in-every.html

**** coreutils gotchas
http://www.pixelbeat.org/docs/coreutils-gotchas.html

**** Magit! A Git Porcelain inside Emacs 			      :emacs:
http://magit.vc/

**** Linux Performance Analysis in 60,000 Milliseconds
http://techblog.netflix.com/2015/11/linux-performance-analysis-in-60s.html

**** Dd - Destroyer of Disks					      :Linux:
http://www.noah.org/wiki/Dd_-_Destroyer_of_Disks

**** Containerizing in the real world . . . of Minecraft	     :docker:
http://googlecloudplatform.blogspot.jp/2015/11/containerizing-in-the-real-world-of-Minecraft.html
*** Dec
**** http2 explained
http://http2-explained.haxx.se/
**** 关于启用 HTTPS 的一些经验分享
https://imququ.com/post/sth-about-switch-to-https.html
**** 3 Second Sandwich —— How do card networks work?		    :payment:
https://getmondo.co.uk/blog/2015/12/02/3-second-sandwich/
**** alda  —— A music programming language for musicians
https://github.com/alda-lang/alda
**** Overlay Network Performance of Docker			      :vxlan:
http://mustafaak.in/2015/12/05/docker-overlay-performance.html
**** If I were designing Python's import from scratch		     :python:
http://www.snarky.ca/if-i-were-designing-imort-from-scratch
**** HTTP/2 is here! Goodbye SPDY? Not quite yet			:tls:
https://blog.cloudflare.com/introducing-http2/
**** The uWSGI Swiss Army Knife					     :python:
https://lincolnloop.com/blog/uwsgi-swiss-army-knife/
**** 可靠分布式系统基础 Paxos 的直观解释
http://drmingdrmer.github.io/tech/distributed/2015/11/11/paxos-slide.html

**** Emacs Lisp Animations
http://dantorop.info/project/emacs-animation/

**** rsync.net: ZFS Replication to the cloud is finally here—and it’s fast
http://arstechnica.com/information-technology/2015/12/rsync-net-zfs-replication-to-the-cloud-is-finally-here-and-its-fast/

**** Spark Streaming 源码解析系列
https://github.com/proflin/CoolplaySpark
**** dotfiles -- Your unofficial guide to dotfiles on GitHub.
https://dotfiles.github.io/
**** To cd or not to cd						      :shell:
http://www.redpill-linpro.com/sysadvent/2015/12/02/cd-tips.html
**** Changing a process’ file descriptor on the fly
http://www.redpill-linpro.com/sysadvent/2015/12/04/changing-a-process-file-descriptor-with-gdb.html
**** Java工程师成神之路
     http://www.hollischuang.com/archives/489
**** IPFS：替代HTTP的分布式网络协议
http://www.infoq.com/cn/articles/ipfs
**** Install Arch Infographic
https://imgur.com/Hokk8sK
**** A Python Interpreter Written in Python
http://aosabook.org/en/500L/a-python-interpreter-written-in-python.html
**** Moores law hits the roof						:cpu:
http://www.agner.org/optimize/blog/read.php?i=417


** 2016
   
*** Jan

**** The Elements of Python Style
https://github.com/amontalenti/elements-of-python-style

**** A Unikernel Firewall for QubesOS
http://roscidus.com/blog/blog/2016/01/01/a-unikernel-firewall-for-qubesos/

**** 32C3 CTF: Docker writeup
https://kitctf.de/writeups/32c3ctf/docker/

**** Zopfli Optimization: Literally Free Bandwidth
http://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/

**** Remap the Kernel						       :rust:
http://os.phil-opp.com/remap-the-kernel.html

**** Why `print` became a function in Python 3
http://www.snarky.ca/why-print-became-a-function-in-python-3

**** intermezzOS						  :kernel:os:
http://intermezzos.github.io/

**** es6-cheatsheet
https://github.com/DrkSephy/es6-cheatsheet

**** Assembly is Too High Level: SIB Doubles
http://xlogicx.net/?p=456

**** A Book about Qt5
http://qmlbook.github.io/

**** Unikernel Systems
http://unikernel.com/

**** dead or alive: Linux LibOS project in 2016
https://github.com/thehajime/blog/issues/1

**** 浏览器端的 9 种缓存机制 					      :cache:
https://linux.cn/article-6833-1.html

****  Inappropriate TCP Resets Considered Harmful
https://tools.ietf.org/html/rfc3360

**** Remap the Kernel
http://os.phil-opp.com/remap-the-kernel.html

**** A Python Interpreter Written in Python
http://aosabook.org/en/500L/a-python-interpreter-written-in-python.html

**** ScyllaDB: world's fastest NoSQL column store database
http://www.scylladb.com/

*** Feb

**** Writing my own init with Go - Part 1
http://www.mustafaak.in/2016/02/08/writing-my-own-init-with-go.html

**** Windows 10 TH2 (v1511) Console Host Enhancements		    :console:
http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-%28v1511%29-Console-Host-Enhancements

**** Terminal codes (ANSI/VT100) introduction			    :console:
http://wiki.bash-hackers.org/scripting/terminalcodes

**** A Better Varargs							  :c:
http://codeacumen.info/post/a-better-varargs/

**** The Princeton Bitcoin textbook is now freely available
https://freedom-to-tinker.com/blog/randomwalker/the-princeton-bitcoin-textbook-is-now-freely-available/

**** Linux: Bash Delete All Files In Directory Except Few
http://www.cyberciti.biz/faq/linux-bash-delete-all-files-in-directory-except-few/
*** Mar
**** Infix Operators in Python
http://tomerfiliba.com/blog/Infix-Operators/
**** The Idiomatic Way to Merge Dictionaries in Python
https://treyhunner.com/2016/02/how-to-merge-dictionaries-in-python/
**** boltons boltons should be builtins
https://boltons.readthedocs.org/en/latest/index.html
**** The origins of the class Meta idiom in python
http://mapleoin.github.io/perma/python-class-meta
**** TCP packet drop analysis			     :tcpdump:retran:network:
http://www.unleashnetworks.com/blog/?p=437
**** Flushing out Leaky Taps v2			      :tshark:retran:network:
http://smusec.blogspot.jp/2012/03/flushing-out-leaky-taps-v2.html
**** Using advanced tcpdump filters				    :tcpdump:
https://support.f5.com/kb/en-us/solutions/public/2000/200/sol2289.html#Uni
**** tcpdump tips
http://blog.mosinu.com/?p=239
**** How the heck does async/await work in Python 3.5?
http://www.snarky.ca/how-the-heck-does-async-await-work-in-python-3-5
**** Installing (encrypted) Arch Linux on an Apple MacBook Pro
https://visual-assault.org/2016/03/05/install-encrypted-arch-linux-on-apple-macbook-pro/
**** Python Mocking 101: Fake It Before You Make It
https://blog.fugue.co/2016-02-11-python-mocking-101.html
**** How does perf work? (in which we read the Linux kernel source)
http://jvns.ca/blog/2016/03/12/how-does-perf-work-and-some-questions/
**** Eliminating Delays From systemd-journald, Part 1
https://coreos.com/blog/eliminating-journald-delays-part-1.html
**** Autoconf Tutorial Part-1
http://www.idryman.org/blog/2016/03/10/autoconf-tutorial-1/
**** LXD 2.0: Blog post series [0/12]				      :linux:
https://www.stgraber.org/2016/03/11/lxd-2-0-blog-post-series-012/
**** Maglev: A Fast and Reliable Software Network Load Balancer
http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44824.pdf
**** Dropping Packets in Ubuntu Linux using tc and iptables
https://sandilands.info/sgordon/dropping-packets-in-ubuntu-linux-using-tc-and-iptables
**** Lossless Gigabit Remote Packet Capture With Linux		    :tcpdump:
http://staff.washington.edu/corey/gulp/
**** Linux Network Stack Administration: A Developer’s Approach
http://opensourceforu.efytimes.com/2009/08/linux-network-stack-administration-a-developers-approach/
**** Understanding and optimizing Network utilization
http://careers.directi.com/display/tu/Understanding+and+optimizing+Network+utilization
**** Using NFQUEUE and libnetfilter_queue		      :iptable:linux:
https://home.regit.org/netfilter-en/using-nfqueue-and-libnetfilter_queue/
**** TCP Performance problems caused by interaction between Nagle’s Algorithm and Delayed ACK :tcptrace:
http://www.stuartcheshire.org/papers/NagleDelayedAck/
*** Apr
****  I stared into the fontconfig, and the fontconfig stared back at me
https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/

**** Linux Troubleshooting Cheatsheet: strace, htop, lsof, tcpdump, iftop & sysdig
https://sysdig.com/blog/linux-troubleshooting-cheatsheet/
**** Python Virtual Environments - a Primer
https://realpython.com/blog/python/python-virtual-environments-a-primer/
**** Bootstrap 4 Cheat Sheet
http://hackerthemes.com/bootstrap-cheatsheet
*** May
**** The Ars guide to building a Linux router from scratch
http://arstechnica.com/gadgets/2016/04/the-ars-guide-to-building-a-linux-router-from-scratch/
**** How To Install Puppet 4 in a Master-Agent Setup on Ubuntu 14.04
https://www.digitalocean.com/community/tutorials/how-to-install-puppet-4-in-a-master-agent-setup-on-ubuntu-14-04
**** A simple way to install and configure puppet on CentOS 6
http://techarena51.com/index.php/a-simple-way-to-install-and-configure-a-puppet-server-on-linux/
**** puppet tutorial -- example42
http://www.example42.com/tutorials/PuppetTutorial
**** uvloop: Blazing fast Python networking
http://magic.io/blog/uvloop-blazing-fast-python-networking/
**** Toil is a workflow engine entirely written in Python
http://toil.readthedocs.io/en/latest/
**** SSH for Fun and Profit
https://karla.io/2016/04/30/ssh-for-fun-and-profit.html
**** Cipherli.st Strong Ciphers for Apache, nginx and Lighttpd
https://cipherli.st/
**** 6-Part Guide to NGINX Application Performance Optimization :tcp:performance:
https://www.maxcdn.com/blog/nginx-application-performance-optimization/
**** SuperTCP                                                   :performance:
https://www.supertcp.com/technology-overview/
**** A list of command line tools for manipulating structured text data :cli:
https://github.com/dbohdan/structured-text-tools
**** Kplugs a user-mode interface for plugging into the linux kernel   :perf:
http://www.kplugs.org/
**** How to turn any syscall into an event: Introducing eBPF Kernel probes
https://blog.yadutaf.fr/2016/03/30/turn-any-syscall-into-event-introducing-ebpf-kernel-probes/
**** Docker for your users - Introducing user namespace
https://blog.yadutaf.fr/2016/04/14/docker-for-your-users-introducing-user-namespace/
**** Real World Microservices: When Services Stop Playing Well and Start Getting Real
https://blog.buoyant.io/2016/05/04/real-world-microservices-when-services-stop-playing-well-and-start-getting-real/
**** Advanced Ping: httping, dnsping, smtpping
http://blog.webernetz.net/2016/05/10/advanced-ping-httping-dnsping-smtpping/
**** Who Needs Git When You Got ZFS?
http://zef.me/blog/6023/who-needs-git-when-you-got-zfs
**** Large (UDP) Packets in IPv6
https://ripe72.ripe.net/wp-content/uploads/presentations/67-2016-05-23-bigipv6.pdf
**** Security brief: CoreOS Linux Alpha remote SSH issue
https://coreos.com/blog/security-brief-coreos-linux-alpha-remote-ssh-issue.html
**** Web-based SSH
https://en.wikipedia.org/wiki/Web-based_SSH
**** A tutorial for porting to autoconf & automake                 :autotool:
http://mij.oltrelinux.com/devel/autoconf-automake/
**** Step-By-Step Example of Autotools for Beginner
http://www.aireadfun.com/blog/2012/12/03/study-automake/
**** The Architecture of Open Source Applications
http://aosabook.org/en/index.html

**** Introduction to the Autotools (autoconf, automake, and libtool)
http://www.dwheeler.com/autotools/
**** netem                                                    :linux:network:
http://www.linuxfoundation.org/collaborate/workgroups/networking/netem

**** Host Tuning                        :tcp:performance:network:optimizatio:
http://fasterdata.es.net/host-tuning/

**** SSH服务的几个超时参数 以及 类似DDOS攻击的方法
https://yq.aliyun.com/articles/57903

**** Greenplum 大集群应该调整的sshd_config配置
http://www.atatech.org/articles/58918
*** Jun
**** 	Sikuli: Automate Anything You See on Screen (sikuli.org)
https://news.ycombinator.com/item?id=11859980

**** Why is a Rust executable large?
https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html
**** Shell Script Mistakes
http://www.pixelbeat.org/programming/shell_script_mistakes.html
**** Use the Unofficial Bash Strict Mode (Unless You Looove Debugging)
http://redsymbol.net/articles/unofficial-bash-strict-mode/
**** Easy Automated Snapshot-Style Backups with Linux and Rsync
http://www.mikerubel.org/computers/rsync_snapshots/
**** linux memory management for servers
https://dom.as/2016/05/13/linux-memory-management-for-servers/
**** Network support for TCP Fast Open
https://www.nanog.org/sites/default/files/Paasch_Network_Support.pdf
**** 10 Articles Every Programmer Must Read
http://javarevisited.blogspot.com/2014/05/10-articles-every-programmer-must-read.html
*** Jul
**** Kent Overstreet is creating bcachefs - a next generation Linux filesystem
https://www.patreon.com/bcachefs
**** Why do we use the Linux kernel's TCP stack?
http://jvns.ca/blog/2016/06/30/why-do-we-use-the-linux-kernels-tcp-stack/
**** How to Monitor Zookeeper
https://blog.serverdensity.com/how-to-monitor-zookeeper/
**** ZooKeeper In The Wild
https://events.linuxfoundation.org/sites/events/files/slides/ZooKeeper%20in%20the%20Wild.pdf
**** Use EJS to Template Your Node Application
https://scotch.io/tutorials/use-ejs-to-template-your-node-application
**** Hadoop architectural overview
https://www.datadoghq.com/blog/hadoop-architecture-overview/
*** Aug
**** HTTP Request Timings with cURL
http://blog.kenweiner.com/2014/11/http-request-timings-with-curl.html
**** WIKIBOOK openssh
https://en.wikibooks.org/wiki/OpenSSH
**** Why GNU Autotools is not my favorite build system
http://voices.canonical.com/jussi.pakkanen/2011/09/13/autotools/
**** TLS has exactly one performance problem: it is not used widely enough.
https://istlsfastyet.com/
**** Job queues, message queues and other queues. Almost all of them in one place.
http://queues.io/
**** Git Workflow Basics
https://blog.codeminer42.com/git-workflow-basics-d405746f6205
**** Introduction 2016 NUMA Deep Dive Series
http://frankdenneman.nl/2016/07/06/introduction-2016-numa-deep-dive-series/
**** gdb Debugging Full Example (Tutorial): ncurses
http://www.brendangregg.com/blog/2016-08-09/gdb-example-ncurses.html
**** TCP Puzzlers
https://www.joyent.com/blog/tcp-puzzlers
**** BPF - the forgotten bytecode
https://blog.cloudflare.com/bpf-the-forgotten-bytecode/
**** New (and Exciting!) Developments in Linux Tracing                  :bpf:
     http://events.linuxfoundation.org/sites/events/files/slides/tracing-linux-ezannoni-linuxcon-ja-2015_0.pdf
**** JIT native code generation for TensorFlow computation graphs using Python and LLVM
http://blog.christianperone.com/2016/08/jit-native-code-generation-for-tensorflow-computation-graphs-using-python-and-llvm/
*** Sep
**** [线上问题] Nginx与Tomcat、Client之间请求的长连接配置不一致问题分析解决 :kee:
http://bert82503.iteye.com/blog/2152613
**** TIME_WAIT问题小结
http://www.zuoqin.me/time_wait%E9%97%AE%E9%A2%98%E5%B0%8F%E7%BB%93/
**** How the Linux kernel knows it’s running in a Virtual Machine       :kvm:
http://perfolys.io/2016/09/06/how-the-linux-kernel-knows-its-running-in-a-virtual-machine/
**** Linux Networking Explained
http://www.slideshare.net/ThomasGraf5/linux-networking-explained
**** If You Like Bonding, You Will Love Teaming               :network:linux:
http://rhelblog.redhat.com/2014/06/23/team-driver/
**** Linux Kernel Tinification
https://tiny.wiki.kernel.org/start
**** Linux Music Workflow: Switching from Mac OS X to Ubuntu with Kim Cascone
http://cdm.link/2009/08/linux-music-workflow-switching-from-mac-os-x-to-ubuntu-with-kim-cascone/
**** Linux system hardening: adding hidepid to /proc
https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/
**** The various IDs of disks, filesystems, software RAID, LVM, et al in Linux
https://utcc.utoronto.ca/~cks/space/blog/linux/IDsForDisksAndFilesystems
**** A Funny Thing Happened on the Way to Java 8              :jvm:codecache:
http://engineering.indeedblog.com/blog/2016/09/job-search-web-app-java-8-migration/
**** So you want your JVM’s heap…
http://blogs.atlassian.com/2013/03/so-you-want-your-jvms-heap/
**** JAVA dump and -F options
http://stackoverflow.com/questions/26140182/running-jmap-getting-unable-to-open-socket-file
**** Docker: Configure Insecure Registry for systemd
http://www.developmentalmadness.com/2016/03/09/docker-configure-insecure-registry-for-systemd/
**** Barriers, Caches, Filesystems                                  :storage:
https://monolight.cc/2011/06/barriers-caches-filesystems/
**** uvloop: Blazing fast Python networking
https://magic.io/blog/uvloop-blazing-fast-python-networking/
**** The Morning Paper on Operability
https://blog.acolyer.org/2016/09/21/the-morning-paper-on-operability/
**** security things in Linux v4.3
https://outflux.net/blog/archives/2016/09/26/security-things-in-linux-v4-3/
**** Tracing on Linux
http://netsplit.com/tracing-on-linux
**** Http 请求头中的 Proxy-Connection
https://imququ.com/post/the-proxy-connection-header-in-http-request.html
*** Oct
**** TCP协议的性能评测工具 — Tcpdive开源啦
http://blog.csdn.net/zhangskd/article/details/50529254
**** FRTO—虚假超时剖析                                                  :tcp:
http://blog.csdn.net/zhangskd/article/details/7446441
**** 每个JavaScript开发者都该懂的Unicode 
http://www.zcfy.cc/article/what-every-javascript-developer-should-know-about-unicode-1303.html
**** Vim: So long Pathogen, hello native package loading
https://shapeshed.com/vim-packages/
*** Nov
**** Comparison of Apache Stream Processing Frameworks: Part 1 :flink:storm:spark:
http://www.cakesolutions.net/teamblogs/comparison-of-apache-stream-processing-frameworks-part-1
**** Puppet 3.7 File Function Improvements
http://www.unixdaemon.net/puppet/puppet-3.7-file-function/
**** Hadoop YARN中内存和CPU两种资源的调度和隔离
http://dongxicheng.org/mapreduce-nextgen/hadoop-yarn-memory-cpu-scheduling/
**** 大数据框架对比：Hadoop、Storm、Samza、Spark和Flink
http://www.infoq.com/cn/articles/hadoop-storm-samza-spark-flink
**** AHCI就要过时了？新接口标准NVMe浅析
http://diy.pconline.com.cn/611/6111798_all.html
*** Dec
**** Why do forked processes sometimes appear with brackets [] around their name in ps? 
http://unix.stackexchange.com/questions/110595/why-do-forked-processes-sometimes-appear-with-brackets-around-their-name-in-p

** 2017
*** Jan
**** Sendfile (a system call for web developers to know about!)
https://jvns.ca/blog/2016/01/23/sendfile-a-new-to-me-system-call/
*** Feb
**** Pretty printing JSON in Vim
https://pascalprecht.github.io/2014/07/10/pretty-print-json-in-vim/
*** Mar
**** 浅析 Linux 初始化 init 系统，第 1 部分: sysvinit
https://www.ibm.com/developerworks/cn/linux/1407_liuming_init1/index.html
**** 浅析 Linux 初始化 init 系统，第 2 部分: UpStart
http://www.ibm.com/developerworks/cn/linux/1407_liuming_init2/
**** 浅析 Linux 初始化 init 系统，第 3 部分: Systemd
https://www.ibm.com/developerworks/cn/linux/1407_liuming_init3/index.html
**** Zone reclaim mode                                         :linux:sysctl:
https://informixdba.wordpress.com/2015/10/16/zone-reclaim-mode/
**** The MySQL “swap insanity” problem and the effects of the NUMA architecture
https://blog.jcole.us/2010/09/28/mysql-swap-insanity-and-the-numa-architecture/
**** NUMA (Non-Uniform Memory Access): An Overview
http://queue.acm.org/detail.cfm?id=2513149
**** A Good Vimrc
https://dougblack.io/words/a-good-vimrc.html
**** Coding for SSDs – Part 1: Introduction and Table of Contents
http://codecapsule.com/2014/02/12/coding-for-ssds-part-1-introduction-and-table-of-contents/
**** 配置 OOM Killer 自动终止内存泄露进程
http://www.noellinux.net/?p=204
**** Cgroup - Linux 的资源隔离
https://www.v2ex.com/member/jerry017cn/topics
*** May
**** Linux OOM killer
https://segmentfault.com/a/1190000008268803
**** How do I get the total CPU usage of an application from /proc/pid/stat?
https://stackoverflow.com/questions/16726779/how-do-i-get-the-total-cpu-usage-of-an-application-from-proc-pid-stat
*** Jun
**** Linux utils that you might not know
http://shiroyasha.io/coreutils-that-you-might-not-know.html
**** How is GNU `yes` so fast?
https://www.reddit.com/r/unix/comments/6gxduc/how_is_gnu_yes_so_fast/
**** Learn X in Y minutes
https://learnxinyminutes.com/docs/shutit/
**** PCIe 4.0 will be twice as fast as today's slots
https://www.engadget.com/2017/06/09/pcie-4-0-twice-as-fast/
**** Using pseudo-terminals (pty) to control interactive programs
http://rachid.koucha.free.fr/tech_corner/pty_pdip.html
**** A few things I've learned about Kubernetes
https://jvns.ca/blog/2017/06/04/learning-about-kubernetes/
**** Cgroup namespace
http://hustcat.github.io/cgroup-namespace/
**** Slab allocators in the Linux Kernel: SLAB, SLOB, SLUB
https://events.linuxfoundation.org/sites/events/files/slides/slaballocators.pdf
**** Attach a volume to a container while it is running
https://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/

*** Jul

**** My Arch Linux Setup with Plasma 5                             :kde:arch:
https://sadanand-singh.github.io/posts/completesetuparchplasma/

**** Exploiting the Linux kernel via packet sockets
https://googleprojectzero.blogspot.jp/2017/05/exploiting-linux-kernel-via-packet.html

**** Dirty COW and why lying is bad even if you are the Linux kernel
https://chao-tic.github.io/blog/2017/05/24/dirty-cow

**** Buffer IO的throttle问题
http://hustcat.github.io/blkcg-buffered-io/

**** stressコマンドの使い方
http://qiita.com/hana_shin/items/b1d8cd559d1a326f4d42

**** Linux Containers Internals (Part I)
http://rabbitstack.github.io/operating%20systems/linux-containers-internals-part-i/

**** Docker Inspect Template Magic
http://container-solutions.com/docker-inspect-template-magic/

**** Linux tracing systems & how they fit together
https://jvns.ca/blog/2017/07/05/linux-tracing-systems/

**** How To Find Out How Long A Process Has Been Running In Linux
https://www.ostechnix.com/find-long-process-running-linux/

**** How Wi-Fi Works
http://www.verizoninternet.com/bookmark/how-wifi-works/

**** How to clear journalctl
https://unix.stackexchange.com/questions/139513/how-to-clear-journalctl

*** Aug

**** Shell Scripts Matter                                              :bash:
https://dev.to/thiht/shell-scripts-matter

**** Docker Reference Architecture: Designing Scalable, Portable Docker Container Networks
https://success.docker.com/Architecture/Docker_Reference_Architecture%3A_Designing_Scalable%2C_Portable_Docker_Container_Networks

**** How to use kdump to debug kernel crashes
https://fedoraproject.org/wiki/How_to_use_kdump_to_debug_kernel_crashes

**** 内核调试工具 — kdump & crash 
http://blog.csdn.net/zhangskd/article/details/38084337

**** Linux Delay Accounting
https://andrestc.com/post/linux-delay-accounting/

**** 10 Tips for Writing Better Code
https://cdiggins.github.io/blog/programming-tips.html

**** Intel® Virtualization Technology (Intel® VT)
https://www.intel.com/content/www/us/en/virtualization/virtualization-technology/intel-virtualization-technology.html

**** Intel® Resource Director Technology
https://www.intel.com/content/www/us/en/architecture-and-technology/resource-director-technology.html

**** AWS EC2 Virtualization 2017
http://www.brendangregg.com/blog/2017-11-29/aws-ec2-virtualization-2017.html

**** AWS EC2 Virtualization 2017
http://www.brendangregg.com/blog/2017-11-29/aws-ec2-virtualization-2017.html

**** How Netflix Tunes EC2 Instances for Performance
https://www.slideshare.net/brendangregg/how-netflix-tunes-ec2-instances-for-performance

**** Disable Transparent Hugepages
https://blog.nelhage.com/post/transparent-hugepages/

*** Sep

**** Deprecated Linux networking commands and their replacements
https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/

**** How to disable IPv6 in Linux?
https://www.blackmoreops.com/2015/08/04/how-to-disable-ipv6-in-linux/

**** What Happens Inside a 100-hop IPv6 Wireless Mesh Network?
http://www.thingsquare.com/blog/articles/100-hops-ipv6-mesh/

**** Welcome to the World of Software Defined Radio
http://www.robertputt.co.uk/welcome-to-the-world-of-software-defined-radio.html

*** Oct

**** Debugging Linux Kernel with QEMU
https://unix.stackexchange.com/questions/61122/debugging-linux-kernel-with-qemu

**** Debugging kernel and modules via gdb
https://www.kernel.org/doc/html/latest/dev-tools/gdb-kernel-debugging.html

**** Build Linux Kernel and Live Debugging
http://accelazh.github.io/kernel/Build-Linux-Kernel-and-Live-Debugging

**** vim-galore
https://github.com/mhinz/vim-galore

**** Linux Perf Tools Tips
http://oliveryang.net/2016/07/linux-perf-tools-tips/#327-error-probe-overhead-exceeded-threshold

**** Reasons Kubernetes is cool
https://jvns.ca/blog/2017/10/05/reasons-kubernetes-is-cool/

**** Filesystem error handling
https://danluu.com/filesystem-errors/

**** Ext4 Project Quota磁盘配额使用介绍
http://blog.csdn.net/luckyapple1028/article/details/75754591

**** OverlayFs wik
https://github.com/amir73il/overlayfs/wiki

**** Bootstrap Kubernetes the hard way on Google Cloud Platform. No scripts.
     https://github.com/kelseyhightower/kubernetes-the-hard-way

**** Understanding user namespaces
http://man7.org/conf/osseu2017/understanding_user_namespaces-OSS.eu-2017-Kerrisk.pdf

**** Nmap Cheat Sheet
https://www.stationx.net/nmap-cheat-sheet/

*** Nov
**** ANALYZING DOCKER CONTAINER PERFORMANCE WITH NATIVE TOOLS
https://crate.io/a/analyzing-docker-container-performance-native-tools/
**** Memory inside Linux containers
https://fabiokung.com/2014/03/13/memory-inside-linux-containers/
**** AWK - Multiple-Line Records
https://www.gnu.org/software/gawk/manual/html_node/Multiple-Line.html
**** MY OPINION ON GO
https://dpc.pw/blog/2016/09/my-opinion-on-go/
**** Perfect locality and three epic SystemTap scripts
https://blog.cloudflare.com/perfect-locality-and-three-epic-systemtap-scripts
**** eBPF 简史
https://www.ibm.com/developerworks/cn/linux/l-lo-eBPF-history/index.html
**** eBPF, part 2: Syscall and Map Types
https://ferrisellis.com/posts/ebpf_syscall_and_maps/
**** dirty_ratio与dirty_background_ratio的区别
https://feichashao.com/dirty_ratio_and_dirty_background_ratio/
**** linux IO 内核参数调优 之 参数调节和场景分析
http://backend.blog.163.com/blog/static/2022941262013112081215609/
**** How to Use Nmap Script Engine (NSE) Scripts in Linux
https://www.tecmint.com/use-nmap-script-engine-nse-scripts-in-linux/#
**** JOB QUEUES IN GO
https://www.opsdash.com/blog/job-queues-in-go.html
**** Understanding Processes in Linux
http://careers.directi.com/display/tu/Understanding+Processes+in+Linux
**** 7 tools for analyzing performance in Linux with bcc/BPF
https://opensource.com/article/17/11/bccbpf-performance
**** Wake up and Shut Down Linux Automatically
https://www.linux.com/learn/intro-to-linux/2017/11/wake-and-shut-down-linux-automatically
**** HHKB 键盘布局配置方案
https://bitmingw.com/2017/07/29/hhkb-keyboard-layout-configuration/
*** Dec
**** Catalog of error handling patterns in Go
http://www.cirello.org/2017/12/catalog-error-handling-patterns-in-go
**** The path of data-link layer(receive)
https://linuxdevicedriver.hackpad.com/The-path-of-data-link-layerreceive-rdh6VtO4SNc

** 2018
*** Jan
**** WebGraphviz is Graphviz in the Browser
http://www.webgraphviz.com/
**** Ten Things I Wish I’d Known About bash
https://zwischenzugs.com/2018/01/06/ten-things-i-wish-id-known-about-bash/
*** Feb
**** 如何通过TTL调试光猫
https://paper.seebug.org/506/
**** Explaining Docker Image IDs
https://windsock.io/explaining-docker-image-ids/
*** Mar
**** 杭州房产知识扫盲
https://houshanren.gitbooks.io/hangzhou_house_knowledge/content/
**** How to Use Socks5 Proxy in Curl
https://blog.emacsos.com/use-socks5-proxy-in-curl.html
**** Kernel Recipes 2017 - 20 years of Linux Virtual Memory
https://www.slideshare.net/ennael/kernel-recipes-2017-20-years-of-linux-virtual-memory-andrea-arcangeli
**** LDD mmap and DMA
http://www.xml.com/ldd/chapter/book/ch13.html
  
*** Apr
**** A list of command line tools for manipulating structured text data
https://github.com/dbohdan/structured-text-tools
*** May
**** How to Turn Vim into a Word Processor
https://www.maketecheasier.com/turn-vim-word-processor/
**** send_signal函数注解
http://www.cnblogs.com/IrisZhou/p/3197050.html
* blog
** Individuals
*** Axb的自我修养
http://blog.2baxb.me/
*** 火丁笔记
http://huoding.com/
*** nixCraft
http://www.cyberciti.biz/
*** mark nottingham
https://www.mnot.net
*** edsionte's TechBlog                                        :linux:kernel:
http://edsionte.com/techblog/
** Companys
*** cloudflare blog
https://blog.cloudflare.com/
*** unitedstack
https://www.ustack.com/blog/
*** CDN Blog - News, Tips & How-To
http://www.cdnplanet.com/blog/
** Organizations
*** Linux Audit - Linux security: Auditing, Hardening and Compliance
http://linux-audit.com/

* Kernel
** live patch
- A rough patch for live patching :: http://lwn.net/Articles/634649/
** network
   
*** userspace network stacks
- Running the kernel in library mode :: http://lwn.net/Articles/639333/
- Library Operating System for Linux  :: http://www.slideshare.net/hajimetazaki/library-operating-system-for-linux-netdev01
- Why do we use the Linux kernel's TCP stack? :: http://jvns.ca/blog/2016/06/30/why-do-we-use-the-linux-kernels-tcp-stack/
*** Queueing in the Linux Network Stack
https://www.coverfire.com/articles/queueing-in-the-linux-network-stack/

*** 内核中拥塞窗口初始值对http性能的影响分析
http://simohayha.iteye.com/blog/709955

*** tcpprobe, observe the TCP flow with kprobes
http://perthcharles.github.io/2014/12/19/tcp-probe-intro/

*** NET_DROP_MONITOR: Monitoring packet loss in the Linux kernel
http://www.draconyx.net/articles/net_drop_monitor-monitoring-packet-loss-in-the-linux-kernel.html

*** dropwatch 网络协议栈丢包检查利器
http://blog.yufeng.info/archives/2497

*** Networking in the Linux Kernel
https://wiki.openwrt.org/doc/networking/praxis

*** Linux Kernel Networking by Rami Rosen 2007
http://www.haifux.org/lectures/172/netLec.pdf

*** Monitoring and Tuning the Linux Networking Stack: Receiving Data     :rx:
http://blog.packagecloud.io/eng/2016/06/22/monitoring-tuning-linux-networking-stack-receiving-data/

*** Monitoring and Tuning the Linux Networking Stack: Sending Data       :tx:
https://blog.packagecloud.io/eng/2017/02/06/monitoring-tuning-linux-networking-stack-sending-data/
*** Navigating the Linux kernel network stack: receive path              :rx:
http://epickrram.blogspot.com/2016/05/navigating-linux-kernel-network-stack.html

*** Illustrated Guide to Monitoring and Tuning the Linux Networking Stack: Receiving Data
https://blog.packagecloud.io/eng/2016/10/11/monitoring-tuning-linux-networking-stack-receiving-data-illustrated/

*** Virtio networking: A case study of I/O paravirtualization :linux:kernel:network:
http://lettieri.iet.unipi.it/virtualization/io-paravirtualization-tour.pdf

*** 10 Gbit Hardware Packet Filtering Using Commodity Network Adapters
http://www.ntop.org/products/packet-capture/pf_ring/hardware-packet-filtering/

*** Linux kernel features for high-speed networking                     :rss:
http://syuu.dokukino.com/2013/05/linux-kernel-features-for-high-speed.html

*** Intel Ethernet Flow Director (Fortville) Video
http://connectedsocialmedia.com/13463/intel-ethernet-flow-director-fortville-video/

*** Linux Kernel Networking by Raoul Rivas 2006                          :tx:
http://web.engr.illinois.edu/~caesar/courses/CS598.S11/slides/raoul_kernel_slides.pdf

*** LinuxCon 2015 Linux Kernel Networking Walkthrough
http://www.slideshare.net/ThomasGraf5/linuxcon-2015-linux-kernel-networking-walkthrough

*** Getting the Best of Both Worlds with Queue Splitting (Bifurcated Driver)
http://rhelblog.redhat.com/2015/10/02/getting-the-best-of-both-worlds-with-queue-splitting-bifurcated-driver/
*** Pushing the Limits of Kernel Networking                         :network:
http://rhelblog.redhat.com/2015/09/29/pushing-the-limits-of-kernel-networking/
*** Snabb Switch: kernel-bypass networking illustrated               :bypass:
https://github.com/lukego/blog/issues/13
*** User Space Networking Fuels NFV Performance                      :bypass:
https://software.intel.com/en-us/blogs/2015/06/12/user-space-networking-fuels-nfv-performance#scratch
*** Diagnosing networking issues in the Linux Kernel             :monitoring:
https://code.mixpanel.com/2015/03/26/diagnosing-networking-issues-in-the-linux-kernel/
*** TUN/TAP devices on Linux
http://recolog.blogspot.com/2016/06/tuntap-devices-on-linux.html
*** Linux 上虚拟网络与真实网络的映射                                 :bridge:
http://www.ibm.com/developerworks/cn/linux/1312_xiawc_linuxvirtnet/
*** Bridge vs Macvlan                                                :bridge:
http://hicu.be/bridge-vs-macvlan
***  网络数据包收发流程(一)：从驱动到协议栈
http://blog.chinaunix.net/uid-24148050-id-464587.html
*** Linux Bridge - how it works
http://goyalankit.com/blog/linux-bridge
** security
*** Auditd - Linux 服务器安全审计工具 
https://linux.cn/article-4907-1.html
*** Linux 用户空间审计系统
http://os.51cto.com/art/201205/337496_all.htm
*** Chapter 7. System Auditing
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/chap-system_auditing.html
*** Audit and Namespaces, future in Containers
http://events.linuxfoundation.org/sites/events/files/slides/lss-2016-audit-namespaces.pdf
*** Audit, namespaces, and containers
https://lwn.net/Articles/699819/

** Misc
*** Linux kernel development
https://github.com/0xAX/linux-insides/blob/master/Misc/contribute.md
*** Tutorial - Write a System Call
https://brennan.io/2016/11/14/kernel-dev-ep3/

*** What is the meaning of "ext[3/4]_dx_add_entry: Directory index full!"? 
https://access.redhat.com/solutions/29894

*** Network Diagnostic Tools
https://wiki.centos.org/Events/Dojo/Bangalore2014?action=AttachFile&do=get&target=Network-jkalliyat.pdf
*** The Definitive Guide to Linux System Calls                      :syscall:
http://blog.packagecloud.io/eng/2016/04/05/the-definitive-guide-to-linux-system-calls/
** Memory
*** Memory Resource Controller
https://events.linuxfoundation.org/images/stories/slides/jls09/jls09_kamezawa.pdf
*** Memory inside Linux containers
https://fabiokung.com/2014/03/13/memory-inside-linux-containers/
*** RHEL memory cgroup
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/sec-memory.html
* Network
** Tcp
*** 浅谈TCP优化
http://huoding.com/2013/11/21/299
*** TCP Window Size Scaling
https://networklessons.com/ip-routing/tcp-window-size-scaling/
*** Linux Kernel 4.9 中的 BBR 算法与之前的 TCP 拥塞控制相比有什么优势？
https://www.zhihu.com/question/53559433/answer/135903103
*** TCP BBR算法学习笔记（1）
http://www.jianshu.com/p/08eab499415a
*** TCP拥塞控制算法 优缺点 适用环境 性能分析
http://blog.csdn.net/zhangskd/article/details/6715751
** Wireless
*** 4.6Gbps Wi-Fi: How 60GHz wireless works—and should you use it?
http://arstechnica.com/gadgets/2016/12/802-11ad-wifi-guide-review/
** Phy
*** Obscure Ethernet for $200 please, Alex: The Ethernet PAUSE frame
http://jeffq.com/blog/the-ethernet-pause-frame/

* Virtualization
** network
*** Network virtualization with VXLAN
http://vincent.bernat.im/en/blog/2012-multicast-vxlan.html
*** Flockport labs - LXC and VXLAN
http://www.flockport.com/flockport-labs-lxc-and-vxlan/
*** Enhanced VXLAN: Who Needs Multicast?
http://adamraffe.com/2013/06/24/enhanced-vxlan-who-needs-multicast/
*** TCP Tuning and Network Troubleshooting                             :cwnd:
http://www.onlamp.com/pub/a/onlamp/2005/11/17/tcp_tuning.html
*** https://medium.com/@loginoff/debugging-a-docker-heisenbug-in-production-586ccb265f7c#.qcbgxybe1
** Container
**** Finally, run systemd containers without privilege !!!           :docker:
http://website-humblec.rhcloud.com/finally-run-systemd-containers-without-privilege/
**** rkt vs other projects
https://coreos.com/rkt/docs/latest/rkt-vs-other-projects.html
**** Borg, Omega, and Kubernetes Lessons learned from three container-management systems over a decade
http://queue.acm.org/detail.cfm?id=2898444
**** Kubernetes: a platform for automating deployment, scaling, and operations
http://www.slideshare.net/BrianGrant11/wso2con-us-2015-kubernetes-a-platform-for-automating-deployment-scaling-and-operations
**** A tale of two clusters: Mesos and YARN
https://www.oreilly.com/ideas/a-tale-of-two-clusters-mesos-and-yarn
**** Gracefully Stopping Docker Containers
https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/
**** Applying mount namespaces
http://www.ibm.com/developerworks/linux/library/l-mount-namespaces/index.html
**** Linux Containers: Parallels, LXC, OpenVZ, Docker and More
https://aucouranton.com/2014/06/13/linux-containers-parallels-lxc-openvz-docker-and-more/
**** 深入理解Docker ulimit
http://dockone.io/article/522
**** Docker Stacks and Attachable networks
http://blog.alexellis.io/docker-stacks-attachable-networks/
**** Deploy the Voting App on a Docker Swarm using Compose version 3
https://medium.com/lucjuggery/deploy-the-voting-apps-stack-on-a-docker-swarm-4390fd5eee4#.k39lrin5b
** Misc
*** virtio: Towards a De-Facto Standard For Virtual I/O Devices
http://ozlabs.org/~rusty/virtio-spec/virtio-paper.pdf
*** Virtio: An I/O virtualization framework for Linux               :virtual:
http://www.ibm.com/developerworks/library/l-virtio/

* Distribution
**  Consistency
*** 分布式一致性论文阅读阶段性小结
http://blog.fnil.net/blog/ac1fa10ff9b2404ed0b91bdfaf76a87d/
* AI
** Deep Learning

*** 普通程序员如何转向AI方向 
http://www.cnblogs.com/subconscious/p/6240151.html
* Communication
** radio
*** 永不消逝的电波（一）：无线电入门篇 
http://www.freebuf.com/articles/wireless/77819.html
*** Welcome to the World of Software Defined Radio
https://www.robertputt.co.uk/2016/12/04/welcome-to-the-world-of-software-defined-radio/
* Security
** ssl
*** The Logjam Attack
https://weakdh.org/
**** Logjam: the latest TLS vulnerability explained
https://blog.cloudflare.com/logjam-the-latest-tls-vulnerability-explained/
*** architecture
https://cloud.google.com/security/security-design/
*** Fuzzing PCI express: security in plaintext
https://cloudplatform.googleblog.com/2017/02/fuzzing-PCI-Express-security-in-plaintext.html-t 
*** 密码学大事件！研究人员公布第一例SHA-1哈希碰撞实例
https://zhuanlan.zhihu.com/p/25401383
* Project
*** OSv operating system
http://osv.io/
*** Viz.js — Graphviz in your browser.
http://mdaines.github.io/viz.js/
*** mermaid Generation of diagram and flowchart from text in a similar manner as markdown
https://github.com/knsv/mermaid
*** netsniff-ng toolkit
http://netsniff-ng.org/
*** PF_RING High-speed packet capture, filtering and analysis.
http://www.ntop.org/products/packet-capture/pf_ring/
*** netmap - the fast packet I/O framework
http://info.iet.unipi.it/~luigi/netmap/
* Command
rsync -avzhP <[[user@]]host1:]directory1> <[[user@]]host2:]directory2>
cat /proc/cpuinfo |grep 'processor\|core id\|physical id'|awk '{print $NF}'| sed 'N;N;s/\n/ /g'|awk '{print $2,$3,$1}'|sort -k1n -k2n -k3n
http://serverfault.com/questions/213119/how-can-i-redirect-an-already-running-processs-stdout-stderr

* References
** lua-users.org							:lua:
http://lua-users.org/
** GNU Screen cheat-sheet
http://neophob.com/2007/04/gnu-screen-cheat-sheet/
* Font & Ideogram 
** What's new in Unicode 9.0 ?
http://babelstone.blogspot.com/2016/01/whats-new-in-unicode-90.html
** The long, incredibly tortuous, and fascinating process of creating a Chinese font
http://qz.com/522079/the-long-incredibly-tortuous-and-fascinating-process-of-creating-a-chinese-font/
** Simply beautiful open source icons
https://feathericons.com/
* Rss
*** inoreader
http://www.inoreader.com/all_articles
*** 深蓝阅读
http://bluereader.org/
